# CONFIG PAGE
# https://alacritty.org/config-alacritty.html

general.import = [
    "~/.config/alacritty/themes/themes/ashes_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12
offset.x = 0
offset.y = 2

[font.normal]
family = "GoMono Nerd Font"
style = "Regular"

[font.bold]
family = "GoMono Nerd Font"
style = "Bold"

[font.italic]
family = "GoMono Nerd Font"
style = "Italic"

[window]
opacity = 0.90

[mouse]
hide_when_typing = true

[cursor]
style.blinking = "Always"

[keyboard]
bindings = [{ key = "C", mods = "Alt", action = "ToggleViMode" }]
