[cursor.style]
blinking = "Always"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
family = "Lilex Nerd Font"
style = "Regular"

[font.bold]
family = "Lilex Nerd Font"
style = "Bold"

[font.italic]
family = "Lilex Nerd Font"
style = "Italic"

[font.offset]
x = 0
y = 3

[general]
import = ["/home/shd/.config/alacritty/themes/themes/ashes_light.toml"]

[[keyboard.bindings]]
action = "ToggleViMode"
key = "C"
mods = "Alt"

[mouse]
hide_when_typing = true

[window]
opacity = 1
