# CONFIG PAGE
# https://alacritty.org/config-alacritty.html

import = ["~/.config/alacritty/themes/carbonfox.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 15
offset.x = 0
offset.y = 2

[font.normal]
#CaskaydiaCove Nerd Font
#NotoMono Nerd Font
family = "Hack Nerd Font"
style = "Regular"

# [font.bold]
# family = "CaskaydiaCove Nerd Font"
# style = "Bold"

[window]
opacity = 0.75

[mouse]
hide_when_typing = true

[cursor]
style.blinking = "Always"

[keyboard]
bindings = [{ key = "V", mods = "Alt", action = "ToggleViMode" }]
