#!/bin/bash

# Get the CPU usage
usage=$(top -bn1 | grep "Cpu(s)" | awk '{print $2 + $4}' | xargs printf "%.0f")
# Get the CPU temperature (assuming the system has sensors installed)
temp=$(sensors | grep 'Tctl' | awk '{print $2}' | tr -d '+')

echo "${usage}%  ${temp}"
