# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


envd = QT_STYLE_OVERRIDE,Adwaita-Dark
envd = QT_QPA_PLATFORMTHEME,Adwaita-Dark

### CURSOR
envd = HYPRCURSOR_THEME,Notwaita-White
envd = QT_CURSOR_SIZE,20
envd = XCURSOR_SIZE,20
env = HYPRCURSOR_SIZE,20

