import = ["~/.config/alacritty/themes/carbonfox.toml"]

# CONFIG PAGE
# https://alacritty.org/config-alacritty.html

[env]
TERM = "xterm-256color"

[font]
size = 11
offset.x = 0
offset.y = 2

[font.normal]
family = "NotoMono Nerd Font"
style = "Regular"

[font.bold]
family = "NotoMono Nerd Font"
style = "Bold"

[window]
opacity = 0.82

[cursor]
style.blinking = "Always"

[keyboard]
bindings = [{ key = "V", mods = "Alt", action = "ToggleViMode" }]
