import = [
    "~/.config/alacritty/themes/dayfox.toml",
]

[env]
TERM = "xterm-256color"

[font]
size = 12
offset.x = 0
offset.y = 2

[font.normal]
family = "NotoMono Nerd Font"
style = "Regular"

[font.bold]
family = "CaskaydiaCove NFM SemiBold"
style = "Bold"

# [font.bold_italic]
# family = "Liberation Mono Italic"
# style = "Bold Italic"

# [font.italic]
# family = "NotoMono Nerd Font"
# style = "Italic"

